Adds docs for TypeGuard type, #10591
python/mypy pull request #10758
Opened 2021-07-02 09:46 UTC by sobolevn

I am writting an article about ``TypeGuard``s and I've noticed that `mypy` does not document how `TypeGuard`s work.

So, here it is!

It has several examples from PEP itself and several custom ones.
I have tried to cover all corner-cases that I am aware of, but possibly there are other details that I've missed.

I would appreciate your feedback! 👍

2021-07-09 00:55 UTC, JelleZijlstra requested changes
Thanks! I have a couple of wording suggestions.

Also, I'm not sure the "Casts" section is the right place for these docs. "More types" is the traditional place for advanced type system features. I'm curious to hear others' opinions.

2021-07-09 00:55 UTC, JelleZijlstra commented on docs/source/casts.rst
> +  def func1(val: List[object]):
```suggestion
  def func1(val: List[object]) -> None:
```

2021-07-09 00:55 UTC, JelleZijlstra commented on docs/source/casts.rst
> +  def func1(val: List[object]):
```suggestion
  def func1(val: List[object]) -> None:
```

2021-07-09 00:55 UTC, JelleZijlstra commented on docs/source/casts.rst
> +Method can also serve as the ``TypeGuard``:
```suggestion
 A method can also serve as the ``TypeGuard``:
```

2021-07-09 00:55 UTC, JelleZijlstra commented on docs/source/casts.rst
> +  def func(to_validate: object):
```suggestion
  def func(to_validate: object) -> None:
```

2021-07-09 08:41 UTC, sobolevn commented
@JelleZijlstra thanks! I thought that "casts" is the closest to type guards. I can move it, no problem.

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +MyPy supports User-Defined Type Guards
```suggestion
Mypy supports User-Defined Type Guards
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +(`PEP-647 <https://www.python.org/dev/peps/pep-0647/>`_).
```suggestion
(:pep:`647`).
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +It is a way for programs to influence conditional
```suggestion
A type guard is a way for programs to influence conditional
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +          reveal_type(val)  # List[object]
```suggestion
          reveal_type(val)  # Reveals List[object]
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +          print(" ".join(val)) # Error: invalid type
```suggestion
          print(" ".join(val)) # Error: incompatible type
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +  from typing import TypeGuard  # use `typing_extensions` for `python<3.10`
```suggestion
  from typing import TypeGuard  # use `typing_extensions` for Python 3.9 and below
```

2021-07-13 18:15 UTC, hauntsaninja commented on docs/source/casts.rst
> +  it would be possible to break type safety.
```suggestion
  Note: since strict narrowing is not enforced, it's easy
  to break type safety.
```

2021-07-13 18:16 UTC, hauntsaninja commented
Thank you for this! Fixed a couple small nits

2021-07-17 12:45 UTC, sobolevn commented
@JelleZijlstra @hauntsaninja so, should I move this to "Advanced types"? Or is "Casts" the proper place? 🙂

2021-07-19 18:28 UTC, hauntsaninja commented
I'd probably put it in "More types" too, but don't feel strongly.

2021-07-22 08:27 UTC, sobolevn commented
Moved! 👍

2021-08-03 12:18 UTC, sobolevn commented
@hauntsaninja @JelleZijlstra friendly ping 🙂

2021-08-03 17:50 UTC, merged

2021-08-03 17:50 UTC, hauntsaninja commented
Thanks again! :-)