Update fine-grained tests to prep for --namespace-packages support
python/mypy pull request #11259
Opened 2021-10-04 05:48 UTC by nipunn1313

These tests were deleting package files, but not the empty
directory, causing those directories to be interpreted as
namespace packages in #9636

## Test Plan

Tried these out on top of #9636 and confirmed they all work. A couple changed error messages - so I needed to add flags for `--namespace-packages`, but figured that's the future anyway, so this is a good thing.

2021-10-04 07:22 UTC, hauntsaninja approved these changes
Thanks! Got pretty thrown off by `Import of "p.a" ignored`. I just didn't realise that finegrained tests set follow_imports = error by default. Feels like there's a shortage of `follow_imports=normal` tests too...

2021-10-04 08:07 UTC, hauntsaninja requested changes
Actually, maybe it's more in the spirit of the `testDeletePackage5` and `testDeletePackage6` to change the commands, since they are trying to pass `p.a` on the command line. E.g., maybe we pass `--explicit-package-bases` or switch to specifying `-m` instead of files.

2021-10-04 15:49 UTC, nipunn1313 commented
> Actually, maybe it's more in the spirit of the `testDeletePackage5` and `testDeletePackage6` to change the commands, since they are trying to pass `p.a` on the command line. E.g., maybe we pass `--explicit-package-bases` or switch to specifying `-m` instead of files.

We still need to provide `--namespace-packages` to make sure that these tests continue to work after #9636.

I can change them to use `-m p` instead of passing all the files individually, though that does seem unrelated to this commit. I can add as a separate commit. It won't really change the output.

2021-10-04 18:19 UTC, hauntsaninja commented
Yes, agreed on passing `--namespace-packages`. My concern was the error messages that look like:
```
main:2: error: Import of "p.a" ignored
main:2: note: (Using --follow-imports=error, module not passed on command line)
```
since when the command is e.g. `mypy main p/a.py p/__init__.py` we are intending to pass `p.a` on the command line.

To that end, I was suggesting something like:
```
 [case testDeletePackage5]
-# cmd1: mypy main p/a.py p/__init__.py
-# cmd2: mypy main p/a.py
-# cmd3: mypy main
+# flags: --namespace-packages
+# cmd1: mypy -m main -m p.a -m p.__init__
+# cmd2: mypy -m main -m p.a
+# cmd3: mypy -m main
```
```
 [case testDeletePackage6]
-# cmd1: mypy p/a.py p/b.py p/__init__.py
-# cmd2: mypy p/a.py p/b.py
-# cmd3: mypy p/a.py p/b.py
+# flags: --namespace-packages
+# cmd1: mypy -m p.a -m p.b -m p.__init__
+# cmd2: mypy -m p.a -m p.b
+# cmd3: mypy -m p.a -m p.b
```
with the hope of changing that middle error message. It looks to me like even with that change we still ignore `p.a`, which is concerning.

I might be missing something obvious though :-)

2021-10-04 19:54 UTC, nipunn1313 commented
I see your point! With namespace packages, `p` should be a namespace package and `p.a` should be a valid package within the namespace package. In that case, this seems like a bug.

2021-10-05 04:42 UTC, hauntsaninja commented
Okay, I took a closer look and the issue seems to be `verify_module`

2021-10-05 05:37 UTC, hauntsaninja commented
Okay, so this is the diff I'm playing around with now. That is, I think at least some of the problem is that the test fixtures were passing in `a` as the module name for `p/a.py` after `__init__.py` was deleted, instead of `p.a`. These changes make it so that I see the build sources I expect over here https://github.com/python/mypy/blob/0860ca7204f716c18dfa014226a2336b71a9841d/mypy/test/testfinegrained.py#L297.

```
diff --git a/mypy/test/testfinegrained.py b/mypy/test/testfinegrained.py
index ed99b4aea..182212823 100644
--- a/mypy/test/testfinegrained.py
+++ b/mypy/test/testfinegrained.py
@@ -84,6 +84,7 @@ class FineGrainedSuite(DataSuite):
 
         options = self.get_options(main_src, testcase, build_cache=False)
         build_options = self.get_options(main_src, testcase, build_cache=True)
+        options.mypy_path.append(test_temp_dir)
         server = Server(options, DEFAULT_STATUS_FILE)
 
         num_regular_incremental_steps = self.get_build_steps(main_src)
diff --git a/test-data/unit/fine-grained-modules.test b/test-data/unit/fine-grained-modules.test
index 50da301aa..5f8314b93 100644
--- a/test-data/unit/fine-grained-modules.test
+++ b/test-data/unit/fine-grained-modules.test
@@ -902,7 +902,7 @@ main:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missin
 main:2: error: Cannot find implementation or library stub for module named "p"
 
 [case testDeletePackage5]
-# flags: --namespace-packages
+# flags: --namespace-packages --explicit-package-bases
 # cmd1: mypy -m main -m p.a -m p.__init__
 # cmd2: mypy -m main -m p.a
 # cmd3: mypy -m main
@@ -917,8 +917,7 @@ def f(x: str) -> None: pass
 [out]
 main:7: error: Argument 1 to "f" has incompatible type "int"; expected "str"
 ==
-main:6: error: Import of "p.a" ignored
-main:6: note: (Using --follow-imports=error, module not passed on command line)
+main:7: error: Argument 1 to "f" has incompatible type "int"; expected "str"
 ==
 main:6: error: Cannot find implementation or library stub for module named "p.a"
 main:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Unfortunately, mypy now silently passes once we delete `p/__init__.py`, it silently infers `p.a.f` as `Any` and we get no errors, instead of the incompatible arg one we want.

2021-11-17 00:32 UTC, nipunn1313 commented
Hiya again! (@hauntsaninja)! Wanted to bump this one.
No rush - just wanted to make sure this didn't get lost.

2021-11-17 03:47 UTC, hauntsaninja approved these changes
Thanks, I think I left this dangling in the hope that I could quickly fix #11322. Clearly that hasn't happened in the last month, so merge it is :-) Thanks for pushing on this!

2021-11-17 03:48 UTC, merged

2021-11-17 03:49 UTC, hauntsaninja commented
Also merged master into #9636