Checks module bodies to be reachable
python/mypy pull request #11361
Opened 2021-10-19 17:01 UTC by sobolevn

This is a very simple change, but now module bodies are also checked to be reachable.
Let's see what effect it will have.

Closes #11331

2021-10-31 17:41 UTC, sobolevn commented on test-data/unit/check-unreachable-code.test
>      assert not isinstance(c, int)
Nope, because we already have tests for explicit `raise`. Here we test `assert False`

2021-10-31 21:00 UTC, hauntsaninja requested changes

2021-10-31 21:00 UTC, hauntsaninja commented on test-data/unit/check-unreachable-code.test
> +def foo(c: int) -> None:  # E: Statement is unreachable
Is this resolved? Afaict the `if False` check should be in its own test case right?

2021-10-31 21:31 UTC, sobolevn commented
@hauntsaninja I forgot to run `git push`  🤦 

```
» git log
commit 2d51fb85261a23242f79e9ffaa4dc95cb7c0c5d0 (HEAD -> issue-11331)
Author: sobolevn <mail@sobolevn.me>
Date:   Fri Oct 22 18:28:03 2021 +0300

    Addresses review
```

2021-10-31 21:36 UTC, hauntsaninja approved these changes
I kind of suspected that :-) Thanks, looks great

2021-10-31 22:00 UTC, merged

2021-11-01 07:27 UTC, harahu commented on test-data/unit/check-unreachable-code.test
>      assert not isinstance(c, int)
Ah, I see. I guess my point is that `assert False` isn't a safe way to block off code. But whether mypy recognizes that or not is a more high level design decision, and not a subject for this PR.