Use list[int] instead of typing.List[int] in generics.rst
python/mypy pull request #11377
Opened 2021-10-23 20:55 UTC by NickCrews

Also change typing.Tuple to tuple, typing.Dict to dict, etc.

Using standard containers is the best practice moving
forward, so we should encourage it in examples.

I just deleted the info about `typing.List` and friends from the
"Generic class internals" section, since that shouldn't be needed
going forward, and I wanted to try to keep this doc as slim as possible.

### Description

Doesn't change behavior

## Test Plan

Haven't tested rebuilding docs, I assume CI will test that if you approve it to run.

2021-10-31 01:07 UTC, hauntsaninja requested changes
Thanks, this looks good :-)

Python 3.9 is new enough that I think it's still worth keeping around the deleted note about indexing builtins and just clarifying that it applies only to Python 3.8 and lower.

2021-11-02 20:19 UTC, NickCrews commented
Sounds good, thanks @hauntsaninja! I added a comment within the code block to make it even more obvious since I thought the modifier in the paragraph before ("For Python 3.8 and below...") would be way too easy to miss.

I stacked a new commit on top so the progression is recorded. The two commits should be squashed when they are actually merged.

2021-11-02 20:44 UTC, hauntsaninja commented on docs/source/generics.rst
> +   >>> # For Python >=3.9, use normal `list[int]` syntax
```suggestion
   >>> # Only relevant for Python 3.8 and below
   >>> # For Python 3.9 onwards, prefer `list[int]` syntax
```

2021-11-02 22:25 UTC, merged

2021-11-02 22:26 UTC, hauntsaninja commented
Thanks!