[docs] add more info to allow_redefinition
python/mypy pull request #11951
Opened 2022-01-10 00:22 UTC by KotlinIsland

I noticed the docs don't mention a rule of `allow_redefinition`

2022-01-11 06:56 UTC, hauntsaninja requested changes
Thanks! IIRC the exact condition is "if the variable has not been used since it was assigned to", e.g. the following is allowed:
```
def process(items: list[str]) -> None:
    # 'items' has type list[str]
    items = [item.split() for item in items]
    # 'items' now has type list[list[str]]
    print(items)
    items = "mypy"
```
(I haven't read that part of the code in a while, so I might be mistaken)

2022-01-12 00:41 UTC, JelleZijlstra commented on docs/source/command_line.rst
> +           items = int(items)  # valid, items not has type int
```suggestion
           items = "100"  # valid, items now has type str
           items = int(items)  # valid, items now has type int
```

2022-01-12 00:45 UTC, KotlinIsland commented on docs/source/command_line.rst
> +           items = int(items)  # valid, items not has type int
oops

2022-01-27 02:06 UTC, JelleZijlstra approved these changes

2022-01-27 02:06 UTC, merged