Move truthy-function docs from “optional checks” to “enabled by default”
python/mypy pull request #14380
Opened 2023-01-03 05:31 UTC by andersk

This error was enabled by default since its introduction (#13686); document it in the correct section.

2023-01-03 12:29 UTC, cdce8p approved these changes
Thanks @andersk! LGTM

2023-01-03 20:03 UTC, hauntsaninja approved these changes
Thanks for spotting this!

2023-01-03 20:04 UTC, hauntsaninja commented on docs/source/error_code_list.rst
> +.. _ignore-without-code:
I think this anchor should not be moved

2023-01-10 06:28 UTC, hauntsaninja requested changes
(for the anchor fix)

2023-01-10 07:00 UTC, andersk commented
Oops, fixed.

2023-01-11 00:25 UTC, merged

2023-01-11 00:25 UTC, hauntsaninja commented
Thank you!