[stubtest] Verify __all__ exists in stub
python/mypy pull request #18005
Opened 2024-10-21 10:56 UTC by srittau

Previously it wasn't an error if runtime included an
`__all__` declaration, but the stubs did not. This PR
changes this to reflect the consensus that it would
be a good idea to ensure consistency in this case.

Fixes #13300

2024-10-21 11:24 UTC, JelleZijlstra commented
Does this cause a lot of new errors in typeshed?

2024-10-21 11:43 UTC, srittau commented
How can we check that? If it does, I suggest we just mass add `.*\.__all__  # TODO` to the stubtest allowlists, like @Avasam suggested.

2024-10-21 16:17 UTC, JelleZijlstra commented
I tried locally (by installing this PR branch and running typeshed tests), and didn't see any new errors—which actually seems a little suspicious.

2024-10-21 16:26 UTC, srittau commented
> I tried locally (by installing this PR branch and running typeshed tests), and didn't see any new errors—which actually seems a little suspicious.

Very. I suspect there to be a quite significant number of hits.

2024-10-21 16:38 UTC, JelleZijlstra commented
It was because of #18007; I forgot that stubtest doesn't do anything if there are mypy errors in the stubs.

With this patch:

<details>

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 46014bcd2..77e5e3127 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -166,3 +166,6 @@ known-first-party = ["ts_utils", "_utils"]
 
 [tool.typeshed]
 oldest_supported_python = "3.8"
+
+[tool.mypy]
+disable_error_code = "deprecated"
diff --git a/tests/stubtest_stdlib.py b/tests/stubtest_stdlib.py
index 5134f8270..77dab3d20 100755
--- a/tests/stubtest_stdlib.py
+++ b/tests/stubtest_stdlib.py
@@ -29,6 +29,8 @@ def run_stubtest(typeshed_dir: Path) -> int:
         "--check-typeshed",
         "--custom-typeshed-dir",
         str(typeshed_dir),
+        "--mypy-config-file",
+        str(typeshed_dir / "pyproject.toml"),
         *allowlist_stubtest_arguments("stdlib"),
     ]
     if sys.version_info < (3, 10):
```

</details>

I get these in the stdlib on macOS and 3.12:

```
error: asyncio.__all__ is not present in stub
error: email.__all__ is not present in stub
error: email._policybase.__all__ is not present in stub
error: importlib.resources.abc.__all__ is not present in stub
error: os.__all__ is not present in stub
error: socket.__all__ is not present in stub
error: xml.__all__ is not present in stub
error: zipfile._path.__all__ is not present in stub
note: unused allowlist entry concurrent.futures.__all__
```

Didn't run it on all the third-party stubs.

2024-10-21 16:38 UTC, JelleZijlstra approved these changes

2024-10-21 16:43 UTC, srittau commented
Interesting. I just commented out `__all__` in stubs/passlib/passlib/utils/__init__.pyi, ran stubtest on passlib and didn't get any warnings. There is `__all__` at runtime.

2024-10-21 16:45 UTC, JelleZijlstra commented
Did you use `stubtest_third_party.py`? Looks like it always installs the mypy from our requirements.txt, so it wouldn't pick up local changes.

2024-10-21 16:47 UTC, srittau commented
Yes, it seems that way. I added debug statements to the installed mypy and those are not printed either.

2024-10-21 16:54 UTC, JelleZijlstra commented
Yes, if you want to test you'll have to edit requirements.txt or otherwise hack the script. I think the stdlib results are enough for me to believe that this works as expected, so I'm happy to merge this, but I'll wait a little bit in case Shantanu/Alex/someone else seeing this has more feedback.

2024-10-21 19:11 UTC, Avasam commented
I do have a question: Do we want to report cases where `__all__` is missing in stubs, but __all__ at runtime is redundant? (ie: already re-exports all symbols). I don't feel strongly either way, I just want to make sure the decision is explicit.

2024-10-21 21:16 UTC, srittau commented
> I do have a question: Do we want to report cases where `__all__` is missing in stubs, but `__all__` at runtime is redundant? (ie: re-exports all symbols anyway, so star-imports wouldn't be affected). I don't feel strongly either way, I just want to make sure the decision is explicit.

I would say yes. Stubs beings closer to the implementation has value in itself, instead of special casing specific cases. Also, it means that `x.__all__` type checks correctly. There might be other use cases that we don't know about yet.

2024-10-21 21:18 UTC, hauntsaninja requested changes

2024-10-21 21:18 UTC, hauntsaninja commented on mypy/stubtest.py
> +            yield Error(object_path + ["__all__"], "is not present in stub", stub, runtime)
```suggestion
            yield Error(object_path + ["__all__"], "is not present in stub", MISSING, runtime)
```

2024-10-21 21:18 UTC, hauntsaninja commented on mypy/test/teststubtest.py
> -        output = run_stubtest(
this test case should still pass (see my suggested change above)

2024-10-23 20:06 UTC, hauntsaninja approved these changes
Thank you!

2024-10-23 20:06 UTC, merged