More LSP compatibility on arg names
python/mypy pull request #18363
Opened 2024-12-29 22:29 UTC by hauntsaninja

Got lost when #18356 was broken up

2024-12-29 22:58 UTC, cdce8p requested changes

2024-12-29 22:58 UTC, cdce8p commented on mypy/plugin.py
> +    def named_type(self, fullname: str, args: list[Type], /) -> Instance:
Changing the argument to `fullname` does make sense. Just not sure about adding `/` though. It feels a bit like an escape hatch. For example it hides the fact that the argument is still named something different in the implementation. I'd suggest removing the `/` here.

https://github.com/python/mypy/blob/ac6151ae6657a8bbd9793c74691c9985dae02c15/mypy/typeanal.py#L1939-L1941

2024-12-29 22:58 UTC, cdce8p commented on mypy/plugin.py
> +    def analyze_type(self, typ: Type, /) -> Type:
Same case here. The `/` feels unnecessary. Changing the argument name to `typ` in the single implementation would probably be better.
https://github.com/python/mypy/blob/ac6151ae6657a8bbd9793c74691c9985dae02c15/mypy/typeanal.py#L1765-L1766

2024-12-29 22:58 UTC, cdce8p commented on mypy/plugin.py
> +        /,
```suggestion
        typ: Type,
```

2024-12-29 22:58 UTC, cdce8p commented on mypy/semanal_shared.py
> +        /,
```suggestion
        typ: Type,
```

2024-12-29 22:58 UTC, cdce8p commented on mypy/plugin.py
> +    def lookup_fully_qualified(self, fullname: str, /) -> SymbolTableNode:
```suggestion
    def lookup_fully_qualified(self, fullname: str) -> SymbolTableNode:
```
I'd again update the implementation instead.
https://github.com/python/mypy/blob/ac6151ae6657a8bbd9793c74691c9985dae02c15/mypy/typeanal.py#L291-L292

2024-12-29 22:58 UTC, cdce8p commented on mypy/semanal_shared.py
> +    def lookup_fully_qualified(self, fullname: str, /) -> SymbolTableNode:
```suggestion
    def lookup_fully_qualified(self, fullname: str) -> SymbolTableNode:
```

2024-12-29 22:58 UTC, cdce8p commented on mypy/plugin.py
> +    def lookup_fully_qualified_or_none(self, fullname: str, /) -> SymbolTableNode | None:
```suggestion
    def lookup_fully_qualified_or_none(self, fullname: str) -> SymbolTableNode | None:
```

2024-12-29 22:58 UTC, cdce8p commented on mypy/semanal_shared.py
> +    def lookup_fully_qualified_or_none(self, fullname: str, /) -> SymbolTableNode | None:
```suggestion
    def lookup_fully_qualified_or_none(self, fullname: str) -> SymbolTableNode | None:
```

2024-12-29 23:04 UTC, hauntsaninja reviewed
I prefer positional-only arguments here, since this is part of mypy's plugin API. This way plugin authors get errors upfront, instead of perhaps later when running their plugin against an older version of mypy.

I can make some of the implementations positional-only too though.

2024-12-29 23:12 UTC, cdce8p commented
> I prefer positional-only arguments here, since this is part of mypy's plugin API. This way plugin authors get errors upfront, instead of perhaps later when running their plugin against an older version of mypy.

Makes sense. The methods marked with pos-only are unlikely to be called with keyword args anyway. Would you mind updating the argument names in the implementation, so that these are at least consistent (i.e. the ones I liked to above)?

2024-12-30 00:13 UTC, cdce8p approved these changes
Thanks @hauntsaninja 👍🏻 
Last thing, could you also update the comment on the API changes issue? _I don't have the permission to do that, unfortunately._

2024-12-30 00:23 UTC, merged