Fix typos discovered by codespell
python/mypy pull request #18387
Opened 2024-12-30 21:54 UTC by cclauss

https://pypi.org/project/codespell

2024-12-30 22:14 UTC, JelleZijlstra commented on mypy/fastparse.py
> +    """Check if an AST contains yields or yield forms."""
"froms" is correct here

2024-12-30 23:26 UTC, cdce8p requested changes
Thanks for the PR! I think `codespell` would be a great addition. Little bit surprised that it didn't find any spelling issues in the changelog though 😄

2024-12-30 23:26 UTC, cdce8p commented on .pre-commit-config.yaml
> +    rev: v2.2.4
```suggestion
    rev: v2.3.0
```
I believe `2.3.0` is the latest release.
https://github.com/codespell-project/codespell/releases/tag/v2.3.0

2024-12-30 23:26 UTC, cdce8p commented on pyproject.toml
> +ignore-words-list = "ans,ccompiler,corus,fo,froms,haa,hax,notin,ot,statics,whet,zar"
2.3.0 added inline ignores. We should probably use those for single occurrences like `froms`.
```py
# codespell:ignore froms
```

2024-12-30 23:26 UTC, cdce8p commented on pyproject.toml
> +skip = "./mypyc/external/*,*.pyi,*.test"
I do wonder if we should just skip the whole `mypy/test/` and `mypyc/test` folders entirely.

Personally I'd also just move the config to `.pre-commit-config.yaml` directly. Don't think any one is ever running codespell outside pre-commit.

This also allows us to use the pre-commit files filter as well with `exclude_types: [pyi, test]` and `exclude: ^(mypyc/external/|mypy/test|mypyc/test)`.

2025-01-21 06:53 UTC, cclauss commented on pyproject.toml
> +ignore-words-list = "ans,ccompiler,corus,fo,froms,haa,hax,notin,ot,statics,whet,zar"
This sounds way too chatty to me.  Putting all the config in one place sounds more intuitive and sensible to me.

2025-01-21 07:08 UTC, cclauss commented on pyproject.toml
> +skip = "./mypyc/external/*,*.pyi,*.test"
Ignoring typos in all tests sounds a bit lazy. I detest those cryptic regex syntaxes and have struggled to make them work in both mypy and black.  I much prefer the config of pytest and ruff which do intuitive filtering without `^(|)` which might be great for computers to parse but is suboptimal for those of us that do not have a masters in computer science degree.

The point of [PEP621](https://peps.python.org/pep-0621) is to concentrate the project config into a canonical file.  Some users may choose to run `codespell` on the command line and it would be a shame if they did so without access to the config that was stored in a hidden file.

2025-01-21 07:10 UTC, cclauss commented
More new typos to fix…
```
mypy/constraints.py:388: unwraped ==> unwrapped
mypyc/doc/dev-intro.md:389: Debuggging ==> Debugging
mypyc/doc/dev-intro.md:412: Instad ==> Instead
mypyc/test/test_run.py:347: Debuggging ==> Debugging
```

2025-02-12 13:39 UTC, closed without merging