Sort mypy.options.PER_MODULE_OPTIONS and fix typo
python/mypy pull request #9469
Opened 2020-09-22 21:02 UTC by e-kwsm

### Description

As the title says.

## Test Plan

The modifications will not affect the current behaviour and CI will pass.

2020-09-22 21:33 UTC, gvanrossum requested changes
Can you undo the changes to mypyc/external/googletest? Those are copied from https://github.com/google/googletest/tree/master/googletest and I don't think there's any point in fixing typos there.

2020-09-22 21:39 UTC, e-kwsm commented
> Can you undo the changes to mypyc/external/googletest?

Done.

2020-09-22 21:58 UTC, hauntsaninja reviewed
I'm curious what you used to find these?

2020-09-22 21:58 UTC, hauntsaninja commented on test-data/unit/fixtures/object_with_init_subclass.pyi
> +# copy passed from primitives.pyi
nit:
```suggestion
# copy pasted from primitives.pyi
```

2020-09-22 22:56 UTC, merged

2020-09-22 22:56 UTC, hauntsaninja commented
Thanks!

2020-09-23 03:11 UTC, e-kwsm commented
I use https://github.com/bwignall/typochecker.